version: 2
jobs:
        build:
                working_directory: ~/repo
                docker: 
                        - image: circleci/openjdk:8-jdk
                        - image: circleci/openjdk:8-jdk-stretch
                branches:
                  only:
                  - develop
                steps:
                        - checkout
                        - restore_cache:
                                key: circleci-ohpen-{{ checksum "pom.xml" }}
                        - run: mvn dependency:go-offline
                        - save_cache: 
                                paths:
                                        - ~/m2
                                key: circleci-ohpen-{{ checksum "pom.xml" }}
                        - run: mvn package
                        - run: mvn surefire-report:report
                        - store_test_results:
                                path: target/surefire-reports
                        - store_artifacts:
                                path: target/ohpen-1.0-SNAPSHOT.jar
